package lib;

public enum TestOrderEnum {
    SUCCESSFUL_OPEN_MAIN_PAGE,
    SUCCESSFUL_OPEN_LOGIN_PAGE,
    FAILED_LOGIN,
    SUCCESSFUL_LOGIN,
    CLICK_3D_CATEGORY,
    BROWSER_BACK,
    NAVIGATE_TO_SETTINGS_PAGE,
    EDIT_BIO,
    SIGN_OUT,
    SEARCH_RANDOM_TEXT,
    SUCCESSFUL_OPEN_SAVE_ASSETS_PAGE,
    CREATE_NEW_LIST_IN_SAVE_ASSETS_PAGE,
    SELECT_CREATED_LIST_IN_SAVE_ASSETS_PAGE,
    DELETE_CREATED_LIST_IN_OWN_LIST_PAGE,
    SUCCESSFUL_OPEN_MY_ASSETS_PAGE,
    SUCCESSFUL_OPEN_PRODUCT_PAGE,
    NAVIGATE_TO_MAIN_PAGE_FROM_PRODUCT_PAGE
}
